rem type http:\\www.google-analytics.com\analytics.js>>appMerged.js
rem type C:\Projects\Git\Sources\HTML5\take5\sdk\TGH5.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\Class.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\io\BitStream.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\utils.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\io\storage.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\media\soundManager.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\leaderBoards\HomeLeaderBoards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\frameWork\demo\DemoModeController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\buttons\generalDialogButtonBig.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\buttons\generalDialogButtonRoundGameOver.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\game_menu.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\quit.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\new_game.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\profile_delete.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\round_message.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\game_over_message.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\game_over_demo_dialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\help.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\home_leaderboards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\main_menu.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\profiles_editing.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\classic.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\pyramid.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\towers.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\screens\scorpion.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\languages\english.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\languages\german.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\languages\french.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\languages\russian.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\resources\languages\spanish.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\config.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\screenHelper.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\cardBank.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\utils.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\Card.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\AbstractCardColumn.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\SelectedCardInfo.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\Profile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\solitaireProfiles.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\classic\ClassicCardColumn.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\classic\ClassicFoundation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\classic\ClassicStockPile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\classic\ClassicWastePile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\classic\ClassicModel.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\pyramid\PyramidCardColumn.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\pyramid\PyramidFoundation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\pyramid\PyramidStockPile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\pyramid\PyramidModel.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\towers\TowersCardColumn.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\towers\TowersFoundation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\towers\TowersStockPile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\towers\TowersModel.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\scorpion\ScorpionCardColumn.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\scorpion\ScorpionStockPile.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\scorpion\ScorpionModel.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\model\solitaireModel.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\solitaireAnimation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\animateWaitStub.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\scoreFly.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\animateCardsMove.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\animateOneCardMove.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\animateCardReveal.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\animateServeCards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\pyramid\pyramidRemoveCards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\pyramid\pyramidServeNextCards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\animations\scorpion\scorpionServeNextCards.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\Button.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\Instruction.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\classic\ClassicView.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\pyramid\PyramidView.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\towers\TowersView.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\scorpion\ScorpionView.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\view\solitaireView.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\mouseController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\ColumnSelection.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\solitaireNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\classic\ClassicNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\pyramid\PyramidNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\towers\TowersNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\scorpion\ScorpionColumnSelection.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\scorpion\ScorpionNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\solitaireController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\NavigableItem.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\AbstractDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\MainMenuDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\HowToPlayDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\GameOverDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\GameOverDemoDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\RoundDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\GameMenuDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\NewGameDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\QuitDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\HomeLeaderBoardsDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\profilesDialog\ProfileDeleteDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\profilesDialog\chooseProfileNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\profilesDialog\editPlayerNavigation.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\dialogs\profilesDialog\ProfilesEditingDialog.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\AbstractCardColumnController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\classic\ClassicCardColumnController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\classic\ClassicFoundationController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\classic\ClassicStockPileController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\classic\ClassicWastePileController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\scorpion\ScorpionCardColumnController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\scorpion\ScorpionStockPileController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\towers\TowersCardColumnController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\towers\TowersFoundationController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\towers\TowersStockPileController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\pyramid\PyramidCardColumnController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\pyramid\PyramidFoundationController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\src\controller\pyramid\PyramidStockPileController.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\loader\resources\loaderScreen.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\loader\resources\imagesList.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\loader\ImageLoader.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\loader\loader.js>>appMerged.js
type C:\Projects\Git\Sources\HTML5\take5\games\solitaireVoyage\loader\startApp.js>>appMerged.js